export enum DomainEventType {
    WORK_ORDER_CREATED = "WORK_ORDER_CREATED",
    WORK_ORDER_ASSIGNED = "WORK_ORDER_ASSIGNED",
    WORK_ORDER_STARTED = "WORK_ORDER_STARTED",
    WORK_ORDER_COMPLETED = "WORK_ORDER_COMPLETED",
    WORK_ORDER_CLOSED = "WORK_ORDER_CLOSED",
    WORK_ORDER_ARCHIVED = "WORK_ORDER_ARCHIVED",
    COMMENT_ADDED = "COMMENT_ADDED",
    MEMBER_ADDED = "MEMBER_ADDED",
    MEMBER_REMOVED = "MEMBER_REMOVED",
    MEMBER_ROLE_CHANGED = "MEMBER_ROLE_CHANGED",
    INVITATION_SENT = "INVITATION_SENT",
    INVITATION_ACCEPTED = "INVITATION_ACCEPTED",
}